language:       generic
sudo:           required
dist:           bionic
git:
  submodules:   false

before_install: 
  - sudo apt-get update -qq
install:
    # install a needed perl module
      #  first install an installer
      -  sudo cpan App::cpanminus
      #  then install the module
      -  sudo cpanm String::ShellQuote
    # install Ubuntu packages
      - sudo add-apt-repository --yes ppa:avsm
      - sudo apt-get install --yes --quiet ocaml opam aspcud time libgtk2.0-dev libgtksourceview2.0-dev emacs
    # set up opam
      - opam init --yes --no-setup
      - eval $(opam config env)
      - opam install lablgtk camlp5 num --yes
before_script:
  - pushd ..        
  - git clone --no-checkout https://github.com/UniMath/UniMath
  - cd UniMath
  - git checkout master
  - git show
  - make PACKAGES="Foundations MoreFoundations Combinatorics Algebra NumberSystems CategoryTheory Topology Ktheory PAdics" install
  - export PATH=$PATH:$PWD/sub/coq/bin/
  - popd
script:
  - make 
